- hosts: routers
  gather_facts: false
  roles:
    - role: community.openwrt.init
      tags: [owrt_init]
    - role: owrt_singbox
      tags: [owrt_singbox, singbox]
    - role: owrt_nfqws
      tags: [owrt_nfqws, nfqws]
    - role: owrt_mgmt
      tags: [owrt_mgmt, mgmt]
