---
- name: reload network
  community.openwrt.command: { cmd: /etc/init.d/network reload }
- name: reload firewall
  community.openwrt.command: { cmd: /etc/init.d/firewall reload }
- name: restart sing-box
  community.openwrt.command: { cmd: service sing-box restart }
- name: restart cron
  community.openwrt.command: { cmd: /etc/init.d/cron restart }
